# Generated by Django 4.1.3 on 2022-12-25 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draw', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_multiplier', models.PositiveIntegerField(verbose_name='Bet multiplier')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bet amount')),
                ('was_rewarded', models.BooleanField(default=False, verbose_name='Was rewarded')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Row Ticket',
                'db_table': 'row_ticket',
            },
        ),
        migrations.CreateModel(
            name='WinningTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_ticket', models.CharField(editable=False, max_length=10, verbose_name='Readable uuid of ticket')),
                ('draw_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.drawresult')),
                ('row_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.rowticket')),
            ],
            options={
                'verbose_name': 'Winning Ticket',
                'db_table': 'winning_ticket',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.PositiveIntegerField(blank=True, null=True, verbose_name='DNI')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('was_printed', models.BooleanField(default=False, verbose_name='Print control')),
                ('is_invalidated', models.BooleanField(default=False, verbose_name='Invalidation control')),
                ('user_commission_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Commission percentage')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('row_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.rowinvoice')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
