# Generated by Django 4.1.3 on 2022-12-13 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RowTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_multiplier', models.PositiveIntegerField(verbose_name='Bet multiplier')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bet amount')),
                ('was_rewarded', models.BooleanField(default=False, verbose_name='Is winner')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'row_ticket',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.PositiveIntegerField(blank=True, null=True, verbose_name='DNI')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('was_printed', models.BooleanField(default=False, verbose_name='Print control')),
                ('is_invalidated', models.BooleanField(default=False, verbose_name='Invalidation control')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
