# Generated by Django 4.1.3 on 2022-11-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RowTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_multiplier', models.PositiveIntegerField(verbose_name='Bet multiplier')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bet amount')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'row_ticket',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.PositiveIntegerField(verbose_name='DNI')),
                ('unique_number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Unique control number')),
                ('was_printed', models.BooleanField(verbose_name='Print control')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
