# Generated by Django 4.1.3 on 2022-12-25 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draw', '0001_initial'),
        ('trade', '0001_initial'),
        ('lottery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rowticket',
            name='draw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.draw'),
        ),
        migrations.AddField(
            model_name='rowticket',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.icon'),
        ),
        migrations.AddField(
            model_name='rowticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.ticket'),
        ),
    ]
