# Generated by Django 4.1.3 on 2023-01-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowticket',
            name='payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment timestamp'),
        ),
    ]
