# Generated by Django 4.1.3 on 2022-12-13 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
        ('trade', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinningTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_ticket', models.CharField(max_length=10, verbose_name='Readable uuid of ticket')),
                ('draw_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.drawresult')),
                ('row_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.rowticket')),
            ],
        ),
    ]
