# Generated by Django 4.1.3 on 2022-12-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='was_printed',
            field=models.BooleanField(default=False, verbose_name='Print control'),
        ),
    ]
