# Generated by Django 4.1.3 on 2022-12-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_winningticket'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='winningticket',
            table='winning_ticket',
        ),
    ]
