# Generated by Django 4.1.3 on 2022-12-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_ticket_was_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Unique control number'),
        ),
    ]
