# Generated by Django 4.1.3 on 2022-12-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_ticket_unique_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_invalidated',
            field=models.BooleanField(default=False, verbose_name='Invalidation control'),
        ),
    ]
