# Generated by Django 4.1.3 on 2022-12-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_winningticket_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningticket',
            name='uuid_ticket',
            field=models.CharField(editable=False, max_length=10, verbose_name='Readable uuid of ticket'),
        ),
    ]
