# Generated by Django 4.1.3 on 2022-12-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_winningticket_uuid_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowticket',
            name='was_rewarded',
            field=models.BooleanField(default=False, verbose_name='Was rewarded'),
        ),
    ]
