# Generated by Django 4.1.3 on 2022-12-19 04:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_total_rewards_invoice_total_rewards_to_pay_and_more'),
        ('trade', '0006_alter_rowticket_was_rewarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_commission',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Commission percentage'),
        ),
    ]
