# Generated by Django 4.1.3 on 2022-12-19 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_ticket_invoice_ticket_user_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_commission',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Commission percentage'),
        ),
    ]
