# Generated by Django 4.1.3 on 2022-12-20 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_commission_percent'),
        ('trade', '0008_alter_ticket_user_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice'),
        ),
    ]
