# Generated by Django 4.1.3 on 2022-12-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_alter_ticket_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user_commission',
            new_name='user_commission_percent',
        ),
    ]
