# Generated by Django 4.1.3 on 2022-12-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_rename_user_commission_ticket_user_commission_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rowticket',
            options={'verbose_name': 'Row Ticket'},
        ),
        migrations.AlterModelOptions(
            name='winningticket',
            options={'verbose_name': 'Winning Ticket'},
        ),
    ]
