# Generated by Django 4.1.3 on 2022-12-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_system_manager',
            field=models.BooleanField(default=False, verbose_name='Lottery System Administrator'),
        ),
    ]
