# Generated by Django 4.1.3 on 2022-12-25 14:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Commission percentage')),
                ('sales_record', models.PositiveIntegerField(default=2147483647, verbose_name='Sales record')),
                ('start_period', models.DateField(default=datetime.date(1, 1, 1))),
                ('end_period', models.DateField(default=datetime.date(9999, 12, 31))),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commission',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_paid', models.BooleanField(default=False, verbose_name='Was paid')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('betting_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.bettingagency')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='RowInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total sales')),
                ('total_rewards', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total sales')),
                ('total_rewards_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total sales')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total commission')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'Row Invoice',
                'db_table': 'row_invoice',
            },
        ),
    ]
