# Generated by Django 4.1.3 on 2022-12-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='sales_record',
            field=models.PositiveIntegerField(default=2147483647, verbose_name='Sales record'),
        ),
    ]
