# Generated by Django 4.1.3 on 2022-12-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='system_commission',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='System Commission Percentage'),
        ),
    ]
