# Generated by Django 4.1.3 on 2022-12-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_commission_sales_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_commission',
            field=models.PositiveIntegerField(default=0, verbose_name='Total commission'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='Total sales'),
        ),
    ]
