# Generated by Django 4.1.3 on 2022-12-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_total_commission_invoice_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_rewards',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total sales'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_rewards_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total sales'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total commission'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total sales'),
        ),
    ]
