# Generated by Django 4.1.3 on 2022-12-19 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_total_rewards_invoice_total_rewards_to_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Commission percentage'),
        ),
    ]
