# Generated by Django 4.1.3 on 2022-12-21 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
        ('invoice', '0005_alter_commission_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingAgencyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_paid', models.BooleanField(default=False, verbose_name='Was paid')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('betting_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.bettingagency')),
            ],
            options={
                'verbose_name': 'Betting Agency - Invoice',
                'db_table': 'betting_agency_invoice',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='betting_agency',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='invoice.bettingagencyinvoice'),
            preserve_default=False,
        ),
    ]
