# Generated by Django 4.1.3 on 2022-12-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingagency',
            name='system_commission',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='System Commission Percentage'),
        ),
    ]
