# Generated by Django 4.1.3 on 2022-12-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingagency',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Betting agency description'),
        ),
    ]
