# Generated by Django 4.1.3 on 2022-12-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_bettingagency_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingagency',
            name='tax_id',
            field=models.CharField(default=0, max_length=15, verbose_name='Tax Identification Number'),
            preserve_default=False,
        ),
    ]
