# Generated by Django 4.1.3 on 2022-12-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_bettingagency_system_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingagency',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Can be operated'),
        ),
    ]
