# Generated by Django 4.1.3 on 2022-12-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_bettingagency_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Can be included in draws'),
        ),
    ]
